Repository revertinc/revert, pull requests merged in 2023-08, with the labels that each got.

#169 feat: move docs to fern
  Dockerfile
  fern/api/definition/connection.yml
  fern/api/definition/crm/proxy.yml
  fern/api/definition/metadata.yml
  fern/api/docs/docs.yml
  fern/api/docs/how-it-works.mdx
  fern/api/docs/intro.mdx
  fern/api/docs/logo.png
  fern/api/docs/pagination.mdx
  fern/api/docs/quick-start.mdx
  fern/api/docs/rate-limits.mdx
  fern/api/docs/versioning.mdx
  fern/api/docs/webhooks.mdx
  packages/backend/config.ts
  packages/backend/helpers/tenantIdMiddleware.ts
  packages/backend/routes/index.ts
  packages/backend/routes/v1/connection/index.ts
  packages/backend/routes/v1/crm/auth.ts
  packages/backend/routes/v1/crm/index.ts
  packages/backend/routes/v1/crm/proxy.ts
  packages/backend/services/auth.ts
  packages/backend/services/connection.ts
  packages/backend/services/crm/index.ts
  packages/backend/services/crm/proxy.ts
  packages/backend/services/proxy.ts
Labels: documentation, feature

#172 hotfix: fix prisma query
  packages/backend/services/connection.ts
Labels: bug

#173 chore(docs): minor update
  README.md
  fern/api/docs/intro.mdx
Labels: documentation

#174 chore: update docs
  README.md
Labels: documentation

#175 chore(docs): improve docs with better explanations
  fern/api/definition/common/types.yml
  fern/api/definition/common/unified.yml
  fern/api/definition/connection.yml
  fern/api/definition/crm/company.yml
  fern/api/definition/crm/contact.yml
  fern/api/definition/crm/deal.yml
  fern/api/definition/crm/event.yml
  fern/api/definition/crm/lead.yml
  fern/api/definition/crm/note.yml
  fern/api/definition/crm/task.yml
  fern/api/definition/crm/user.yml
  fern/api/docs/docs.yml
  fern/api/docs/mdx/how-it-works.mdx
  fern/api/docs/mdx/intro.mdx
  fern/api/docs/mdx/pagination.mdx
  fern/api/docs/mdx/quick-start.mdx
  fern/api/docs/mdx/rate-limits.mdx
  fern/api/docs/mdx/versioning.mdx
  fern/api/docs/mdx/webhooks.mdx
Labels: documentation

#176 chore(docs): add navlinks
  fern/api/docs/docs.yml
  fern/fern.config.json
Labels: documentation

#177 chore: add db backup scripts
  README.md
  packages/backend/routes/index.ts
  scripts/backend/backup_rds.sh
  scripts/backend/backup_table.sh
Labels: chore, internal

#178 fix: add allowlist on rate limiter
  packages/backend/index.ts
Labels: bug

#179 chore(docs): update webhook consumer + docs
  .yarn/install-state.gz
  fern/api/docs/mdx/webhooks.mdx
  package.json
  packages/backend/package.json
  yarn.lock
Labels: documentation, chore

#183 chore(docs): update readme
  README.md
  packages/backend/README.md
Labels: documentation

#184 enhancement: add github action to build js sdk
  .github/workflows/deploy-js-sdk.yaml
Labels: enhancement

#185 add step to upload to s3 & update cloudfront
  .github/workflows/deploy-js-sdk.yaml
Labels: enhancement, chore

#188 enhancement: add workspace name on integration dashboard
  packages/backend/prisma/migrations/20230814121503_1/migration.sql
  packages/backend/prisma/schema.prisma
  packages/backend/services/auth.ts
  packages/client/src/home/index.tsx
  packages/client/src/home/navbar.tsx
Labels: enhancement, UI

#189 fix: add trust proxy value on rate limiter
  packages/backend/index.ts
Labels: bug

#190 chore(repo): add dependabot
  .github/dependabot.yml
  .gitignore
Labels: chore, internal

#196 chore(repo): link sdks with github repo correctly
  .yarn/install-state.gz
  packages/react/package.json
  packages/vue/package.json
Labels: chore, internal, dependencies

#203 feat: encrypt pii data
  packages/backend/config.ts
  packages/backend/helpers/gcmUtil.ts
  packages/backend/prisma/client.ts
  packages/backend/services/connection.ts
  scripts/backend/encrypt_customerEmails.js
Labels: enhancement, feature, security

#206 chore(docs): add contributors list to readme
  README.md
Labels: documentation

#217 feat: add whitelisted domains that can have priority access
  packages/backend/config.ts
  packages/backend/services/auth.ts
Labels: enhancement

#218 chore(docs): move doc generation to a different gh action
  .github/workflows/deploy-fern-docs.yml
  .yarn/install-state.gz
  Dockerfile
Labels: documentation, chore

#219 chore(docs-gen): update node version
  .github/workflows/deploy-fern-docs.yml
Labels: documentation, chore
