Repository revertinc/revert, pull requests merged in 2023-11, with the labels that each got.

#342 chore(repo): add hacker news badge
  README.md
Labels: documentation, chore

#343 chore(repo): improve backend readme for setup locally
  CONTRIBUTING.md
  README.md
  packages/backend/README.md
  packages/backend/package.json
  packages/react/.env.example
  packages/vue/.env.example
Labels: documentation, chore

#347 #261/devex
  fern/api/docs/mdx/developer-guides.mdx
Labels: documentation

#348 chore(docs): add use case section
  fern/api/docs/docs.yml
  fern/api/docs/mdx/usecases.mdx
Labels: documentation

#349 nit: fix typo in docs
  fern/api/docs/docs.yml
  fern/api/docs/mdx/usecases.mdx
Labels: documentation

#351 docs: update supported APIs and remove crm specific terms
  fern/api/docs/docs.yml
  fern/api/docs/mdx/crm-supported.mdx
  fern/api/docs/mdx/how-it-works.mdx
  fern/api/docs/mdx/intro.mdx
  fern/api/docs/mdx/messaging-supported.mdx
  fern/api/docs/mdx/usecases.mdx
Labels: documentation, enhancement

#352 feat: add conventional commits check
  .github/workflows/check-pr-title.yml
Labels: enhancement, internal, oss

#354 docs: re-organise into tabs with upgraded fern and pr previews
  .github/workflows/deploy-fern-docs.yml
  .github/workflows/preview-docs.yml
  README.md
  fern/api/docs/docs.yml
  fern/definition/api.yml
  fern/definition/chat/channels.yml
  fern/definition/chat/messages.yml
  fern/definition/chat/users.yml
  fern/definition/common/associations.yml
  fern/definition/common/errors.yml
  fern/definition/common/types.yml
  fern/definition/common/unified.yml
  fern/definition/connection.yml
  fern/definition/crm/company.yml
  fern/definition/crm/contact.yml
  fern/definition/crm/deal.yml
  fern/definition/crm/event.yml
  fern/definition/crm/field-mapping/field-mapping.yml
  fern/definition/crm/lead.yml
  fern/definition/crm/note.yml
  fern/definition/crm/properties.yml
  fern/definition/crm/proxy.yml
  fern/definition/crm/task.yml
  fern/definition/crm/user.yml
  fern/definition/internal/account.yml
  fern/definition/metadata.yml
  fern/docs.yml
  fern/docs/assets/favicon.ico
  fern/docs/assets/logo.png
  fern/docs/contents/crm-supported.mdx
  fern/docs/contents/developer-guides.mdx
  fern/docs/contents/how-it-works.mdx
  fern/docs/contents/intro.mdx
  fern/docs/contents/messaging-supported.mdx
  fern/docs/contents/pagination.mdx
  fern/docs/contents/quick-start.mdx
  fern/docs/contents/rate-limits.mdx
  fern/docs/contents/usecases.mdx
  fern/docs/contents/versioning.mdx
  fern/docs/contents/webhooks.mdx
  fern/fern.config.json
  fern/generators.yml
  package.json
Labels: documentation, enhancement

#355 chore: upgrade fern dev dependency
  package.json
  yarn.lock
Labels: chore

#356 fix: fix gh workflow for fern docs
  .github/workflows/deploy-fern-docs.yml
  fern/generators.yml
Labels: chore

#358 fix: docker build with correct fern version
  packages/backend/Dockerfile
Labels: bug, internal

#359 fix: correct fern auto-gen filepath
  fern/generators.yml
Labels: bug

#360 feat: add event delete api endpoint
  fern/definition/crm/event.yml
  packages/backend/services/crm/event.ts
Labels: integration, feature

#361 fix: cleanup self hosted runner directory after job
  .github/workflows/deploy-db-changes.yml
Labels: chore, internal

#362 fix: upgrade `actions/checkout@v4`
  .github/workflows/deploy-db-changes.yml
Labels: bug, internal

#363 fix: handle multiple source field names for same target field name wh…
  packages/backend/helpers/crm/transform/transformSchemaMapping.ts
Labels: bug

#365 feat: json formatted logs for better analytics
  packages/backend/index.ts
Labels: enhancement

#366 fix: hotfix for allowing event creation on pipedrive
  packages/backend/services/crm/event.ts
Labels: bug

#367 fix: update docs accent color
  fern/docs.yml
Labels: bug, documentation

#379 feat: add onboarding page on dashboard
  packages/client/src/home/index.tsx
  packages/client/src/home/onboarding.tsx
Labels: documentation, UI
