Repository revertinc/revert, pull requests merged in 2023-10, with the labels that each got.

#276 chore: add lodash types
  .yarn/install-state.gz
  packages/backend/package.json
  yarn.lock
Labels: chore

#277 chore: skip health-check logs
  packages/backend/index.ts
Labels: chore

#280 feat: add custom properties api for pipedrive
  fern/api/definition/crm/properties.yml
  packages/backend/services/crm/properties.ts
Labels: feature

#281 chore(docs): update readme
  .yarn/install-state.gz
  README.md
  public/github_readme.jpg
Labels: documentation

#282 chore(repo): update cal link
  README.md
Labels: documentation, chore

#290 enhancement: 1. update integration dashboard ux 2. add dotenv for js
  .yarn/install-state.gz
  packages/client/package.json
  packages/client/src/App.css
  packages/client/src/home/environmentSelector.tsx
  packages/client/src/home/navbar.tsx
  packages/client/src/routes/index.tsx
  packages/js/.env.example
  yarn.lock
Labels: enhancement

#291 chore(deps): remove unused across different packages
  .yarn/cache/react-script-hook-npm-1.7.2-891b438492-74fb5ec2e6.zip
  .yarn/install-state.gz
  packages/backend/package.json
  packages/client/package.json
  packages/js/package.json
  packages/react/package.json
  packages/vue/package.json
  yarn.lock
Labels: chore

#293 add FUNDING.yml
  .github/FUNDING.yml
Labels: chore, oss

#294 chore: update to a direct open collective link
  .github/FUNDING.yml
Labels: chore, oss

#295 chore(docs): update readme & public docs with connection flow diagram
  README.md
  fern/api/docs/mdx/how-it-works.mdx
  public/connection_flow.png
Labels: documentation, chore

#296 chore(docs): add architecture overview diagram
  README.md
  fern/api/docs/mdx/how-it-works.mdx
Labels: documentation, chore, oss

#317 feat: add analytics on app ui
  packages/client/public/index.html
  packages/client/src/home/apiKeys.tsx
  packages/client/src/home/editCredentials.tsx
  packages/client/src/routes/index.tsx
Labels: enhancement

#318 1. enhancement: add default timestamps across tables
  .github/workflows/deploy-db-changes.yml
  packages/backend/prisma/migrations/20231018074238_1/migration.sql
  packages/backend/prisma/schema.prisma
Labels: enhancement, internal

#319 fix: add yarn install on build step
  .github/workflows/deploy-db-changes.yml
Labels: bug

#320 feat: add api analytics
  .github/workflows/deploy-db-changes.yml
  .yarn/install-state.gz
  packages/backend/.env.example
  packages/backend/config.ts
  packages/backend/index.ts
  packages/backend/package.json
  packages/backend/services/metadata.ts
  yarn.lock
Labels: enhancement, analytics

#325 feat: add webhooks for slack connections
  packages/backend/routes/v1/chat/auth.ts
  packages/backend/routes/v1/crm/auth.ts
Labels: enhancement, integration

#327 fix: create apps only when not present
  packages/backend/services/auth.ts
Labels: bug

#330 chore(docs): update sdk readme
  packages/react/README.md
  packages/vue/README.md
Labels: documentation, chore

#331 chore(repo): bump sdk versions
  packages/react/package.json
  packages/vue/package.json
Labels: chore

#333 feat: seed data via docker compose
  .env.example
  README.md
  docker-compose.yml
  package.json
  packages/backend/db-seed.Dockerfile
  packages/backend/package.json
  packages/backend/prisma/seed.ts
Labels: enhancement, feature, self-hosting

#334 fix: ensure react/next/vue sdks get the right cdn path from env
  packages/js/package.json
  packages/react/.env.example
  packages/react/package.json
  packages/react/src/lib/useRevertConnect.ts
  packages/react/vite.config.ts
  packages/vue/.env.example
  packages/vue/package.json
  packages/vue/src/lib/useRevertConnect.ts
  packages/vue/vite.config.ts
Labels: bug

#335 Typo in documentation
  CONTRIBUTING.md
Labels: documentation, good first issue

#338 chore: update readme
  .env.example
  packages/backend/README.md
  packages/vue/package.json
Labels: documentation, chore

#339 chore(dev-ex): make moesif optional for local dev
  packages/backend/index.ts
Labels: chore, internal

#340 fix: only call `onClose` when passed via props
  packages/js/src/index.ts
Labels: bug
