Repository revertinc/revert, pull requests merged in 2023-12, with the labels that each got.

#400 feat: [internal] alert on slack for new users
  packages/backend/services/auth.ts
Labels: internal

#401 docs: update dev guide with instructions on clerk
  README.md
  fern/docs/contents/developer-guides.mdx
  packages/client/.env.example
Labels: documentation, self-hosting

#403 chore(docs): update readme with launch socials
  README.md
Labels: documentation

#402 refactor: make `prisma db-seed` idempotent
  packages/backend/helpers/crm/transform/transformSchemaMapping.ts
  packages/backend/prisma/fields.ts
  packages/backend/prisma/migrations/20231215090630_testing_cascade_delete/migration.sql
  packages/backend/prisma/migrations/20231215091025_deleting_cascade/migration.sql
  packages/backend/prisma/migrations/20231215094002_testing_referential_update/migration.sql
  packages/backend/prisma/migrations/20231215104815_delete_cascade/migration.sql
  packages/backend/prisma/schema.prisma
  packages/backend/prisma/seed.ts
  packages/react/package.json
  yarn.lock
Labels: enhancement, self-hosting

#410 docs: add steps to setup clerk for auth
  README.md
  fern/docs/contents/developer-guides.mdx
Labels: documentation

#411 docs: highlight cloud version in quickstart
  README.md
  packages/react/README.md
Labels: documentation

#413 feat: deploy images to docker hub via gh action
  .env.example
  .github/workflows/deploy-docker-to-hub.yml
  docker-compose.yml
Labels: internal, self-hosting

#414 fix: set env variables before build stage
  .github/workflows/deploy-docker-to-hub.yml
Labels: internal, self-hosting

#415 debug: add debug logs on ci
  .github/workflows/deploy-docker-to-hub.yml
Labels: internal

#416 fix: path on docker build
  .github/workflows/deploy-docker-to-hub.yml
Labels: internal
