Repository revertinc/revert, pull requests merged in 2023-07, with the labels that each got.

#122 add blurring of secrets and visibility controls
  packages/client/src/home/index.tsx
  packages/client/src/routes/index.tsx
Labels: UI

#123 enhancement: improve dx of building TS SDK
  .yarn/install-state.gz
  packages/js/package.json
  packages/js/tsconfig.json
  packages/react/.gitignore
  packages/react/src/lib/revert-dev.js
  packages/react/src/lib/useRevertConnect.ts
  yarn.lock
Labels: enhancement

#124 feat: custom app credentials w/ Revert APIs
  packages/backend/services/auth.ts
  packages/client/src/home/apiKeys.tsx
  packages/client/src/home/index.tsx
  packages/client/src/home/integrations.tsx
  packages/client/src/home/navbar.tsx
Labels: feature, UI

#125 hotfix: fix clientId mismatch
  packages/backend/prisma/migrations/20230706100606_1/migration.sql
  packages/backend/prisma/schema.prisma
  packages/backend/routes/v1/crm/auth.ts
  packages/backend/services/auth.ts
Labels: bug

#126 chore: update pipedrive logo
  packages/backend/routes/v1/metadata.ts
Labels: sdk

#127 chore: capture remaining exceptions
  packages/backend/helpers/authMiddleware.ts
  packages/backend/helpers/logError.ts
  packages/backend/helpers/tenantIdMiddleware.ts
  packages/backend/routes/index.ts
  packages/backend/routes/v1/connection/index.ts
  packages/backend/routes/v1/crm/auth.ts
  packages/backend/routes/v1/crm/company.ts
  packages/backend/routes/v1/crm/contact.ts
  packages/backend/routes/v1/crm/deal.ts
  packages/backend/routes/v1/crm/event.ts
  packages/backend/routes/v1/crm/lead.ts
  packages/backend/routes/v1/crm/note.ts
  packages/backend/routes/v1/crm/proxy.ts
  packages/backend/routes/v1/crm/task.ts
  packages/backend/routes/v1/crm/user.ts
  packages/backend/routes/v1/metadata.ts
  packages/backend/services/auth.ts
  packages/backend/services/connection.ts
Labels: reliability

#129 chore: add discord link
  README.md
Labels: documentation

#130 Update credentials ui
  packages/backend/routes/index.ts
  packages/backend/services/auth.ts
  packages/client/package.json
  packages/client/src/data/axios/index.ts
  packages/client/src/data/hooks/index.ts
  packages/client/src/data/localstorage/index.ts
  packages/client/src/home/editCredentials.tsx
  packages/client/src/home/integrations.tsx
  yarn.lock
Labels: enhancement, UI

#131 fix: handle old accounts
  packages/backend/services/auth.ts
Labels: bug

#135 feat: toggle to switch revert app
  packages/backend/routes/index.ts
  packages/backend/routes/v1/crm/auth.ts
  packages/backend/routes/v1/metadata.ts
  packages/backend/services/auth.ts
  packages/client/src/home/editCredentials.tsx
Labels: enhancement, feature

#137 fix: improve error messages on webhook dupes
  packages/backend/services/connection.ts
Labels: bug

#138 feat: add webhook verification via svix
  packages/backend/config.ts
  packages/backend/helpers/verifyRevertWebhook.ts
  packages/backend/routes/index.ts
  packages/backend/services/connection.ts
Labels: webhook

#141 chore: add template for PRs
  .github/PULL_REQUEST_TEMPLATE/revert-pr-template.md
Labels: documentation

#143 chore: move default pr
  .github/pull_request_template.md
Labels: documentation

#145 feat: add get webhook endpoint
  packages/backend/routes/v1/connection/index.ts
  packages/backend/services/connection.ts
Labels: enhancement, webhook

#144 feat: pipedrive search apis
  packages/backend/constants/hubspot.ts
  packages/backend/constants/index.ts
  packages/backend/constants/pipedrive.ts
  packages/backend/constants/salesforce.ts
  packages/backend/constants/zoho.ts
  packages/backend/helpers/hubspot.ts
  packages/backend/models/unified/contact.ts
  packages/backend/models/unified/deal.ts
  packages/backend/models/unified/lead.ts
  packages/backend/models/unified/note.ts
  packages/backend/services/contact.ts
  packages/backend/services/deal.ts
  packages/backend/services/lead.ts
  packages/backend/services/metadata.ts
  packages/backend/services/note.ts
  packages/backend/services/proxy.ts
Labels: enhancement, feature

#146 feat: create default environments
  packages/backend/package.json
  packages/backend/prisma/migrations/20230719095257_1/migration.sql
  packages/backend/prisma/migrations/20230719102118_1/migration.sql
  packages/backend/prisma/schema.prisma
  packages/backend/routes/index.ts
  packages/backend/services/auth.ts
  packages/client/src/home/apiKeys.tsx
  packages/client/src/home/editCredentials.tsx
  packages/client/src/home/integrations.tsx
Labels: enhancement

#155 feat: api environments
  .yarn/install-state.gz
  packages/backend/helpers/authMiddleware.ts
  packages/backend/helpers/tenantIdMiddleware.ts
  packages/backend/package.json
  packages/backend/prisma/migrations/20230719095257_1/migration.sql
  packages/backend/prisma/migrations/20230719102118_1/migration.sql
  packages/backend/prisma/migrations/20230719122943_1/migration.sql
  packages/backend/prisma/migrations/20230719130119_1/migration.sql
  packages/backend/prisma/migrations/20230719130722_1/migration.sql
  packages/backend/prisma/migrations/20230719143634_1/migration.sql
  packages/backend/prisma/schema.prisma
  packages/backend/prisma/seed.ts
  packages/backend/routes/index.ts
  packages/backend/routes/v1/crm/auth.ts
  packages/backend/routes/v1/metadata.ts
  packages/backend/services/auth.ts
  packages/backend/services/connection.ts
  packages/backend/services/metadata.ts
  packages/client/src/home/apiKeys.tsx
  packages/client/src/home/editCredentials.tsx
  packages/client/src/home/environmentSelector.tsx
  packages/client/src/home/index.tsx
  packages/client/src/home/integrations.tsx
  packages/client/src/home/navbar.tsx
Labels: enhancement, feature

#157 chore: add manual migrations scripts
  packages/backend/package.json
  packages/backend/prisma/scripts/backward.sql
Labels: chore

#158 hotfix: fix webhooks
  packages/backend/routes/v1/crm/auth.ts
Labels: bug

#159 fix error
  packages/backend/services/connection.ts
Labels: bug

#160 chore: remove log on refresh
  packages/backend/services/auth.ts
Labels: chore

#161 feat: add shortloop
  .yarn/install-state.gz
  packages/backend/config.ts
  packages/backend/index.ts
  packages/backend/package.json
  yarn.lock
Labels: documentation, chore

#162 chore: add logs
  packages/backend/helpers/tenantIdMiddleware.ts
Labels: chore

#163 enhancement: update css
  packages/client/src/home/environmentSelector.tsx
Labels: enhancement

#164 reliability: add sentry tracing on ui
  .yarn/install-state.gz
  package.json
  packages/client/package.json
  packages/client/src/common/oauth/index.tsx
  packages/client/src/home/apiKeys.tsx
  packages/client/src/home/index.tsx
  packages/client/src/home/integrations.tsx
  packages/client/src/index.tsx
  yarn.lock
Labels: reliability, chore

#152 feat: Move endpoints to fern
  fern/api/definition/api.yml
  fern/api/definition/common/errors.yml
  fern/api/definition/common/types.yml
  fern/api/definition/common/unified.yml
  fern/api/definition/crm/company.yml
  fern/api/definition/crm/contact.yml
  fern/api/definition/crm/deal.yml
  fern/api/definition/crm/event.yml
  fern/api/definition/crm/lead.yml
  fern/api/definition/crm/note.yml
  fern/api/definition/crm/task.yml
  fern/api/definition/crm/user.yml
  fern/api/definition/internal/account.yml
  fern/api/definition/metadata.yml
  fern/api/docs/docs.yml
  fern/api/docs/favicon.ico
  fern/api/docs/intro.mdx
  fern/api/docs/logo.png
  fern/api/generators.yml
  fern/fern.config.json
  package.json
  packages/backend/constants/index.ts
  packages/backend/models/unified/deal.ts
  packages/backend/package.json
  packages/backend/routes/index.ts
  packages/backend/routes/v1/crm/company.ts
  packages/backend/routes/v1/crm/contact.ts
  packages/backend/routes/v1/crm/deal.ts
  packages/backend/routes/v1/crm/event.ts
  packages/backend/routes/v1/crm/index.ts
  packages/backend/routes/v1/crm/lead.ts
  packages/backend/routes/v1/crm/note.ts
  packages/backend/routes/v1/crm/task.ts
  packages/backend/routes/v1/crm/user.ts
  packages/backend/services/Internal/account.ts
  packages/backend/services/auth.ts
  packages/backend/services/company.ts
  packages/backend/services/contact.ts
  packages/backend/services/crm/company.ts
  packages/backend/services/crm/contact.ts
  packages/backend/services/crm/deal.ts
  packages/backend/services/crm/event.ts
  packages/backend/services/crm/index.ts
  packages/backend/services/crm/lead.ts
  packages/backend/services/crm/note.ts
  packages/backend/services/crm/task.ts
  packages/backend/services/crm/user.ts
  packages/backend/services/deal.ts
  packages/backend/services/event.ts
  packages/backend/services/lead.ts
  packages/backend/services/metadata.ts
  packages/backend/services/note.ts
  packages/backend/services/task.ts
  packages/backend/services/user.ts
  packages/client/src/constants.ts
  packages/client/src/data/hooks/index.ts
  packages/client/src/home/editCredentials.tsx
  packages/client/src/home/environmentSelector.tsx
  packages/client/src/home/index.tsx
  packages/client/src/home/integrations.tsx
Labels: documentation, enhancement, feature
