Repository revertinc/revert, pull requests merged in 2023-09, with the labels that each got.

#220 :herb: fix fern generate
  .github/workflows/deploy-fern-docs.yml
  package.json
  yarn.lock
Labels: bug, documentation

#226 chore(deps): combine dependabot updates
  .github/workflows/deploy-fern-docs.yml
  .yarn/cache/@babel-core-npm-7.17.8-dc1954857c-0e686b1be4.zip
  .yarn/install-state.gz
  packages/backend/package.json
  packages/client/package.json
  packages/js/package.json
  packages/react/package.json
  packages/vue/package.json
  yarn.lock
Labels: dependencies

#227 feat: add connection ids & make encryption work
  packages/backend/config.ts
  packages/backend/helpers/gcmUtil.ts
  packages/backend/helpers/tenantIdMiddleware.ts
  packages/backend/package.json
  packages/backend/prisma/client.ts
  packages/backend/prisma/migrations/20230904142724_1/migration.sql
  packages/backend/prisma/schema.prisma
  packages/backend/routes/v1/crm/auth.ts
  packages/backend/services/auth.ts
  packages/backend/services/connection.ts
  yarn.lock
Labels: enhancement

#228 hotfix: fix delete connection endpoint
  .yarn/install-state.gz
  packages/backend/services/connection.ts
Labels: bug

#231 chore(docs): update integration roadmap, add new CRMs and others
  README.md
Labels: documentation

#232 chore: update favicon link and add new sign-in route
  packages/client/public/index.html
  packages/client/src/routes/index.tsx
Labels: enhancement

#233 chore(repo): update license
  LICENSE.txt
Labels: chore

#234 chore(repo): add contributing.md
  CONTRIBUTING.md
  README.md
Labels: documentation

#240 chore(repo): update docker compose instructions
  .env.example
  README.md
Labels: documentation

#241 add CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: chore

#254 chore(repo): add a script to use gcm outside service
  .prettierignore
  scripts/backend/decrypt_email.js
Labels: chore

#255 chore: allow everyone to sign up & add better logging
  .yarn/install-state.gz
  packages/backend/helpers/authMiddleware.ts
  packages/backend/helpers/logger.ts
  packages/backend/helpers/tenantIdMiddleware.ts
  packages/backend/routes/index.ts
  packages/backend/routes/v1/crm/auth.ts
  packages/backend/services/Internal/account.ts
  packages/backend/services/auth.ts
  packages/backend/services/connection.ts
  packages/backend/services/crm/company.ts
  packages/backend/services/crm/contact.ts
  packages/backend/services/crm/deal.ts
  packages/backend/services/crm/event.ts
  packages/backend/services/crm/lead.ts
  packages/backend/services/crm/note.ts
  packages/backend/services/crm/proxy.ts
  packages/backend/services/crm/task.ts
  packages/backend/services/crm/user.ts
  packages/backend/services/metadata.ts
Labels: chore

#256 chore: move logs to a single func
  packages/backend/helpers/tenantIdMiddleware.ts
  packages/backend/routes/v1/crm/auth.ts
  packages/backend/services/auth.ts
Labels: chore

#263 chore: refine docs
  fern/api/definition/common/unified.yml
Labels: documentation

#264 chore(docs): update fern ymls with correct description
  fern/api/definition/common/unified.yml
  fern/api/definition/crm/contact.yml
  fern/api/definition/crm/deal.yml
  fern/api/definition/crm/event.yml
  fern/api/definition/crm/lead.yml
  fern/api/definition/crm/note.yml
  fern/api/definition/crm/task.yml
  fern/api/definition/crm/user.yml
Labels: documentation, chore

#265 improve logs
  packages/backend/services/Internal/account.ts
Labels: chore

#266 chore: remove waitlisting
  .yarn/install-state.gz
  packages/backend/prisma/migrations/20230929015544_1/migration.sql
  packages/backend/prisma/schema.prisma
Labels: chore

#267 chore(repo): fix builds
  packages/backend/Dockerfile
Labels: bug

#268 fix build cache attempt
  packages/backend/Dockerfile
Labels: bug
