Repository revertinc/revert, pull requests merged in 2023-06, with the labels that each got.

#70 fix: handle associations while creating notes for hubspot
  packages/backend/models/unified/note.ts
Labels: bug

#71 fix: allow proxy post calls on hubspot
  packages/backend/services/proxy.ts
Labels: bug

#73 feat: add connection api
  packages/backend/index.ts
  packages/backend/routes/connection/index.ts
  packages/backend/services/connection.ts
Labels: feature

#74 Make dealname default in search api
  packages/backend/models/unified/note.ts
  packages/backend/services/deal.ts
Labels: enhancement

#75 feat: add `onClose` implimentation
  packages/js/src/index.ts
  packages/react/src/App.tsx
Labels: enhancement

#76 feat: add get all connections endpoint
  packages/backend/routes/connection/index.ts
  packages/backend/services/connection.ts
Labels: enhancement

#77 fix: bug with incorrect response
  packages/backend/services/connection.ts
Labels: bug

#78 feat: add delete connection api
  packages/backend/helpers/tenantIdMiddleware.ts
  packages/backend/routes/connection/index.ts
  packages/backend/services/connection.ts
Labels: enhancement, feature

#79 feat(reliability): add sentry monitoring
  .yarn/install-state.gz
  packages/backend/config.ts
  packages/backend/index.ts
  packages/backend/package.json
  packages/backend/routes/index.ts
  yarn.lock
Labels: enhancement

#80 feat: add connection webhook api
  .yarn/install-state.gz
  packages/backend/config.ts
  packages/backend/package.json
  packages/backend/routes/connection/index.ts
  packages/backend/services/connection.ts
  packages/react/package.json
  yarn.lock
Labels: enhancement, feature

#84 feat: send events when connections update
  packages/backend/routes/crm/auth.ts
  packages/backend/services/connection.ts
Labels: enhancement, feature

#85 feat: webhook connection events
  packages/backend/routes/crm/auth.ts
  packages/backend/services/connection.ts
Labels: enhancement, feature

#87 chore: better webhook payloads
  packages/backend/routes/crm/auth.ts
  packages/backend/services/connection.ts
Labels: enhancement

#93 chore: remove unused peer-dependency
  .yarn/install-state.gz
  package.json
  packages/react/package.json
  yarn.lock
Labels: bug, sdk

#94 feat: make unified fields optional in `fields` params
  packages/backend/models/unified/company.ts
  packages/backend/services/company.ts
  packages/backend/services/contact.ts
  packages/backend/services/deal.ts
  packages/backend/services/event.ts
  packages/backend/services/lead.ts
  packages/backend/services/note.ts
  packages/backend/services/task.ts
  packages/backend/services/user.ts
Labels: enhancement

#97 fix: react versions conflict
  .yarn/install-state.gz
  packages/react/package.json
Labels: bug, sdk

#99 chore: add sentry catchall-handler
  packages/backend/index.ts
Labels: reliability

#101 feat: management UI v0
  .yarn/install-state.gz
  packages/backend/helpers/isWorkEmail.ts
  packages/backend/package.json
  packages/backend/prisma/migrations/20230626120239_1/migration.sql
  packages/backend/prisma/migrations/20230626142116_1/migration.sql
  packages/backend/prisma/migrations/20230626144136_1/migration.sql
  packages/backend/prisma/migrations/20230626145244_1/migration.sql
  packages/backend/prisma/schema.prisma
  packages/backend/routes/index.ts
  packages/backend/services/auth.ts
  packages/client/package.json
  packages/client/public/index.html
  packages/client/src/App.css
  packages/client/src/assets/images/logo.png
  packages/client/src/home/index.tsx
  packages/client/src/home/navbar.tsx
  packages/client/src/routes/index.tsx
  yarn.lock
Labels: feature

#104 chore: update og image for ui
  packages/client/public/index.html
Labels: enhancement

#106 chore: update readme
  README.md
Labels: documentation

#107 chore: update readme
  README.md
Labels: documentation

#108 chore: update readme
  README.md
Labels: documentation

#110 chore: cleanup readme
  packages/js/README.md
Labels: documentation

#111 chore: update readme
  README.md
Labels: documentation

#102 feat: oauth flow via customer apps
  packages/backend/constants/index.ts
  packages/backend/prisma/migrations/20230626152627_add_scope_to_account/migration.sql
  packages/backend/prisma/migrations/20230627062354_drop_scope_from_accounts/migration.sql
  packages/backend/prisma/migrations/20230628045235_use_client_custom_app_creds/migration.sql
  packages/backend/prisma/migrations/20230628061559_create_app_table/migration.sql
  packages/backend/prisma/migrations/20230628150321_link_app_connection/migration.sql
  packages/backend/prisma/migrations/20230629051826_/migration.sql
  packages/backend/prisma/schema.prisma
  packages/backend/prisma/seed.ts
  packages/backend/routes/v1/crm/auth.ts
  packages/backend/routes/v1/metadata.ts
  packages/backend/services/auth.ts
  packages/backend/services/connection.ts
  packages/js/src/index.ts
  packages/js/vite.config.js
Labels: enhancement

#113 feat: oauth flow via customer apps and granular permissions
  packages/backend/constants/index.ts
  packages/backend/package.json
  packages/backend/prisma/migrations/20230626152627_add_scope_to_account/migration.sql
  packages/backend/prisma/migrations/20230627062354_drop_scope_from_accounts/migration.sql
  packages/backend/prisma/migrations/20230628045235_use_client_custom_app_creds/migration.sql
  packages/backend/prisma/migrations/20230628061559_create_app_table/migration.sql
  packages/backend/prisma/migrations/20230628150321_link_app_connection/migration.sql
  packages/backend/prisma/migrations/20230629051826_/migration.sql
  packages/backend/prisma/schema.prisma
  packages/backend/prisma/seed.ts
  packages/backend/routes/v1/connection/index.ts
  packages/backend/routes/v1/crm/auth.ts
  packages/backend/routes/v1/metadata.ts
  packages/backend/services/auth.ts
  packages/backend/services/connection.ts
  packages/js/src/index.ts
  packages/js/vite.config.js
Labels: enhancement, feature

#115 fix: incorrect creds on ui
  packages/backend/routes/index.ts
  packages/backend/services/auth.ts
  packages/client/src/home/index.tsx
Labels: bug

#118 chore: add `.gitattributes`
  .gitattributes
Labels: ops

#119 chore: update readme
  README.md
Labels: documentation
