Repository revertinc/revert, pull requests merged in 2024-05, with the labels that each got.

#554 chore: update openint requests
  packages/backend/config.ts
  packages/backend/services/custom/twenty.ts
Labels: bug, chore, sync

#553 feat: only create apps that are needed by a developer
  fern/definition/internal/account.yml
  packages/backend/oas/openapi.yml
  packages/backend/services/Internal/account.ts
  packages/backend/services/app.ts
  packages/backend/services/auth.ts
  packages/client/src/features/integration/AddIntegration.tsx
  packages/client/src/features/integration/CreatedIntegration.tsx
  packages/client/src/features/integration/enums/metadata.ts
  packages/client/src/home/environmentSelector.tsx
  packages/client/src/home/integrations.tsx
  packages/client/src/home/navbar.tsx
  packages/client/src/layout/MainHeader.tsx
Labels: 🙋 Bounty claim

#565 fix: non updation of tenantId in useRevertConnect
  packages/react/src/lib/useRevertConnect.ts
Labels: bug, sdk

#567 chore: bump react sdk after upgrade fix
  packages/react/package.json
Labels: chore

#568 chore: bump react sdk version
  packages/react/package.json
Labels: chore

#571 chore: bump react sdk version to `0.0.20`
  packages/react/package.json
Labels: chore

#573 fix: rate limiter fix not working
  packages/backend/helpers/rateLimitMiddleware.ts
Labels: bug
