Repository revertinc/revert, pull requests merged in 2024-03, with the labels that each got.

#500 feat: add field mapping management apis
  fern/definition/crm/field-mapping.yml
  fern/definition/crm/field-mapping/field-mapping.yml
  packages/backend/helpers/tenantAuthMiddleware.ts
  packages/backend/helpers/tenantIdMiddleware.ts
  packages/backend/prisma/schema.prisma
  packages/backend/routes/index.ts
  packages/backend/routes/v1/crm/fieldMapping.ts
  packages/js/package.json
  packages/js/scripts/watch-ts.sh
  packages/js/src/index.ts
Labels: enhancement, feature

#489 refactor: integrations auth
  packages/backend/constants/common.ts
  packages/backend/helpers/auth/baseOAuthHandler.ts
  packages/backend/helpers/auth/processOAuthResult.ts
  packages/backend/helpers/webhooks/connection.ts
  packages/backend/routes/v1/chat/auth.ts
  packages/backend/routes/v1/chat/authHandlers/discord.ts
  packages/backend/routes/v1/chat/authHandlers/slack.ts
  packages/backend/routes/v1/crm/auth.ts
  packages/backend/routes/v1/crm/authHandlers/close.ts
  packages/backend/routes/v1/crm/authHandlers/hubspot.ts
  packages/backend/routes/v1/crm/authHandlers/ms_dynamic_365.ts
  packages/backend/routes/v1/crm/authHandlers/pipedrive.ts
  packages/backend/routes/v1/crm/authHandlers/sfdc.ts
  packages/backend/routes/v1/crm/authHandlers/zoho.ts
  packages/backend/routes/v1/ticket/auth.ts
  packages/backend/routes/v1/ticket/authHandlers/clickup.ts
  packages/backend/routes/v1/ticket/authHandlers/jira.ts
  packages/backend/routes/v1/ticket/authHandlers/linear.ts
  packages/backend/routes/v1/ticket/authHandlers/trello.ts
  packages/backend/services/connection.ts
Labels: refactor

#502 chore(dev-ex): add open api spec
  fern/generators.yml
  packages/backend/.gitignore
  packages/backend/oas/openapi.yml
Labels: chore, dev-ex

#505 chore: allow manual deploys of gh workflows
  .github/workflows/deploy-fern-docs.yml
  .github/workflows/deploy-js-sdk.yaml
Labels: chore

#510 docs: Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation

#511 feat: show object name in field mapping ui
  packages/js/src/index.ts
Labels: enhancement, sdk

#509 docs: docs improvement for integrating apps and local setup
  fern/docs/contents/add-integration-guide.mdx
  fern/docs/contents/developer-guides.mdx
Labels: documentation

#514 feat: update & enhance dashboard ui
  packages/client/src/App.css
  packages/client/src/home/environmentSelector.tsx
  packages/client/src/home/index.tsx
  packages/client/src/home/integrations.tsx
  packages/client/src/home/navbar.tsx
  packages/client/src/home/onboarding.tsx
Labels: enhancement, UI

#515 refactor: modularise app configurations on ui
  packages/client/src/home/environmentSelector.tsx
  packages/client/src/home/integrations.tsx
Labels: UI, refactor

#516 fix: add request integration button back
  packages/client/src/home/index.tsx
Labels: UI, refactor

#517 feat: field mapping api enhancements
  fern/definition/connection.yml
  fern/definition/field-mapping.yml
  packages/backend/oas/openapi.yml
  packages/backend/routes/index.ts
  packages/backend/routes/v1/crm/index.ts
  packages/backend/routes/v1/fieldMapping.ts
  packages/backend/services/connection.ts
  packages/client/src/home/index.tsx
  packages/js/src/index.ts
Labels: bug, enhancement, feature

#518 feat: add `isCustomField` property to crm properties api
  fern/definition/connection.yml
  fern/definition/crm/properties.yml
  packages/backend/oas/openapi.yml
  packages/backend/services/crm/properties.ts
Labels: enhancement

#520 fix: ensure default env is set on integration dashboard
  packages/client/src/home/index.tsx
  scripts/backend/backup_rds.sh
Labels: bug

#507 feat: added bitbucket issue integration
  fern/definition/ticket/comment.yml
  fern/definition/ticket/task.yml
  packages/backend/config.ts
  packages/backend/constants/common.ts
  packages/backend/helpers/crm/transform/disunify.ts
  packages/backend/helpers/crm/transform/preprocess.ts
  packages/backend/prisma/fields.ts
  packages/backend/prisma/migrations/20240305191556_bitbucket/migration.sql
  packages/backend/prisma/schema.prisma
  packages/backend/prisma/seed.ts
  packages/backend/routes/v1/ticket/auth.ts
  packages/backend/routes/v1/ticket/authHandlers/bitbucket.ts
  packages/backend/services/auth.ts
  packages/backend/services/metadata.ts
  packages/backend/services/ticket/collection.ts
  packages/backend/services/ticket/comment.ts
  packages/backend/services/ticket/proxy.ts
  packages/backend/services/ticket/task.ts
  packages/backend/services/ticket/user.ts
  packages/client/src/common/oauth/index.tsx
  packages/client/src/home/integrations.tsx
  packages/js/src/index.ts
Labels: integration, feature, ticketing

#527 fix: indendation
  fern/definition/ticket/task.yml
Labels: bug

#526 docs: integration guide for bitbucket
  fern/docs/contents/guides/bitbucket.mdx
Labels: documentation

#529 fix: correct bitbucket guide link
  fern/docs.yml
Labels: documentation
