Repository revertinc/revert, pull requests merged in 2024-01, with the labels that each got.

#422 fix: add workaround for client build to pass in `.env`
  packages/client/.env.example
Labels: bug, internal

#423 feat: add ability to self host with a different postgres & redis instance
  docker-compose.yml
  fern/docs.yml
  fern/docs/contents/docker-compose.mdx
Labels: feature, self-hosting

#424 ci: ensure images are rebuilt everytime
  .github/workflows/deploy-docker-to-hub.yml
  packages/backend/db-seed.Dockerfile
Labels: internal, self-hosting

#425 feat: add scarf for OSS analytics
  fern/docs/contents/docker-compose.mdx
  fern/docs/contents/intro.mdx
  packages/react/package.json
  packages/vue/package.json
  yarn.lock
Labels: feature, analytics

#431 feat: v1 telemetry when using oss version
  fern/definition/internal/telemetry.yml
  packages/backend/.env.example
  packages/backend/config.ts
  packages/backend/index.ts
  packages/backend/package.json
  packages/backend/prisma/migrations/20240108103913_1/migration.sql
  packages/backend/prisma/schema.prisma
  packages/backend/routes/index.ts
  packages/backend/services/Internal/telemetry.ts
  packages/backend/services/metrics.ts
  yarn.lock
Labels: analytics, self-hosting

#433 chore(repo): add API status badge on repo
  README.md
Labels: documentation

#443 fix: ensure environment selector is working
  packages/client/src/home/analytics.tsx
  packages/client/src/home/environmentSelector.tsx
  packages/client/src/home/index.tsx
Labels: bug, UI

#388 feat: Linear and Clickup ticketing apps integration
  fern/definition/common/types.yml
  fern/definition/common/unified.yml
  fern/definition/ticket/collection.yml
  fern/definition/ticket/comment.yml
  fern/definition/ticket/proxy.yml
  fern/definition/ticket/task.yml
  fern/definition/ticket/user.yml
  packages/backend/.env.example
  packages/backend/config.ts
  packages/backend/constants/common.ts
  packages/backend/helpers/authMiddleware.ts
  packages/backend/helpers/crm/transform/disunify.ts
  packages/backend/helpers/crm/transform/preprocess.ts
  packages/backend/helpers/crm/transform/transformSchemaMapping.ts
  packages/backend/helpers/crm/transform/unify.ts
  packages/backend/helpers/endPointLoggerMiddleWare.ts
  packages/backend/helpers/tenantIdMiddleware.ts
  packages/backend/index.ts
  packages/backend/models/unified/ticketComment.ts
  packages/backend/models/unified/ticketTask.ts
  packages/backend/models/unified/ticketUsers.ts
  packages/backend/package.json
  packages/backend/prisma/fields.ts
  packages/backend/prisma/migrations/20231204082429_ticketing_enums_added/migration.sql
  packages/backend/prisma/migrations/20231208045745_jira_enum_added/migration.sql
  packages/backend/prisma/schema.prisma
  packages/backend/prisma/seed.ts
  packages/backend/routes/index.ts
  packages/backend/routes/v1/ticket/auth.ts
  packages/backend/routes/v1/ticket/index.ts
  packages/backend/services/Internal/analytics.ts
  packages/backend/services/auth.ts
  packages/backend/services/crm/company.ts
  packages/backend/services/crm/contact.ts
  packages/backend/services/crm/event.ts
  packages/backend/services/crm/note.ts
  packages/backend/services/crm/task.ts
  packages/backend/services/metadata.ts
  packages/backend/services/ticket/collection.ts
  packages/backend/services/ticket/comment.ts
  packages/backend/services/ticket/proxy.ts
  packages/backend/services/ticket/task.ts
  packages/backend/services/ticket/user.ts
  packages/client/src/common/oauth/index.tsx
  packages/client/src/home/editCredentials.tsx
  packages/client/src/home/integrations.tsx
  packages/js/src/index.ts
  yarn.lock
Labels: feature, ticketing

#444 fix: add ms integration in metadata api response
  packages/backend/services/metadata.ts
Labels: bug

#452 feat: add python & node-ts sdks
  .github/workflows/deploy-fern-docs.yml
  fern/generators.yml
Labels: feature, sdk, dev-ex

#453 fix: ensure fern token is present
  .github/workflows/deploy-fern-docs.yml
Labels: documentation, dev-ex

#454 docs: add backend sdk references
  fern/docs/contents/quick-start.mdx
Labels: documentation

#458 docs: add integration guides for supported APIs
  fern/docs.yml
  fern/docs/contents/crm-supported.mdx
  fern/docs/contents/guides/clickup.mdx
  fern/docs/contents/guides/close.mdx
  fern/docs/contents/guides/discord.mdx
  fern/docs/contents/guides/hubspot.mdx
  fern/docs/contents/guides/jira.mdx
  fern/docs/contents/guides/linear.mdx
  fern/docs/contents/guides/pipedrive.mdx
  fern/docs/contents/guides/salesforce.mdx
  fern/docs/contents/guides/slack.mdx
  fern/docs/contents/guides/trello.mdx
  fern/docs/contents/guides/zoho-crm.mdx
  fern/docs/contents/messaging-supported.mdx
  fern/docs/contents/ticketing-supported.mdx
  fern/docs/contents/usecases.mdx
Labels: documentation, dev-ex

#462 docs: fix path relative path for quick start
  fern/docs/contents/intro.mdx
Labels: documentation
