Repository revertinc/revert, pull requests merged in 2024-02, with the labels that each got.

#475 fix: handle ui when no analytics data is present
  packages/client/src/home/analytics.tsx
Labels: bug

#477 docs: update `developer-guides.mdx` with steps to install PostgreSQL
  fern/docs/contents/developer-guides.mdx
Labels: documentation

#486 docs: ensure `additional` block is present in docs
  fern/definition/common/unified.yml
  fern/definition/crm/contact.yml
  fern/definition/crm/deal.yml
  fern/definition/crm/event.yml
  fern/definition/crm/lead.yml
  fern/definition/crm/note.yml
  fern/definition/crm/task.yml
  fern/definition/crm/user.yml
Labels: documentation, dev-ex

#487 docs: fix `associations` in reads
  fern/definition/common/unified.yml
Labels: documentation

#497 fix: ensure field mapping config gets the right config
  packages/backend/helpers/tenantAuthMiddleware.ts
Labels: bug

#498 fix: ensure correct middleware gets used
  packages/backend/helpers/tenantAuthMiddleware.ts
  packages/backend/routes/v1/crm/fieldMapping.ts
Labels: bug

#499 fix: get correct t_id config
  packages/backend/helpers/tenantAuthMiddleware.ts
  packages/js/src/index.ts
Labels: bug
